### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by travisfont** [jupitern/Scheduler#1]
Does this schedule work through the browser and command line? Also, does it keep a PHP instance alive on the server the entire time until the final schedule time is met?

I see no information regarding this, so I ask! Cool project, simple code.

**Comment by lenamtl** [comment]
+1
 I need instruction too

**Comment by jupitern** [comment]
Hey,
The solo purpose of this package is to generate dates based on a set of rules. 
I use it with combined with package https://github.com/jupitern/dispatcher that runs jobs with one or more tasks (I will post documentation on that soon). Each time a job starts I use this package to schedule the next job execution.
I then created one task on windows task manager or a cron job on linux to start a thread and execute whatever jobs that execution date <= current date.
More cronjobs = more jobs being processed in parallel.

I would advise against but if you must have a thread always running you could do something like:

```
$schedules = \Jupitern\Scheduler\Scheduler::instance()
    ->addRecurring('+2 seconds')
    ->getNextSchedules('+2 seconds', 5);

foreach ($schedules as $schedule) {
    echo 'sleep until '. $schedule->format('Y-m-d H:i:s').'<br/>';
    time_sleep_until($schedule->getTimestamp());
    echo 'wake up and run tasks here at '. $schedule->format('Y-m-d H:i:s').'<br/>';

    // do what you need here
}
```

**Comment by travisfont** [comment]
Interesting stuff! More documentation never helps :] kudos.
